# Generated by Django 5.2.4 on 2025-07-04 15:32

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Qeyd: maximum 200 simvol', max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('image', models.ImageField(blank=True, help_text='Qeyd: şəklin ölçüsü 870 x 450 px olmalıdır', upload_to='blog_images/')),
                ('short_description', models.CharField(help_text='Qeyd: maximum 200 simvol', max_length=255)),
                ('author_name', models.CharField(help_text='Qeyd: maximum 100 simvol', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('full_description', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
