# Generated by Django 5.1.6 on 2025-07-03 15:06

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('icon_class', models.CharField(help_text='Example: tji-service-1', max_length=100)),
                ('short_description', models.CharField(max_length=255)),
                ('full_description', ckeditor.fields.RichTextField()),
                ('image', models.ImageField(blank=True, upload_to='service_images/')),
            ],
        ),
    ]
