# Generated by Django 5.2.4 on 2025-07-04 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='icon_class',
            field=models.CharField(help_text='Nümunə: tji-service-1, tji-service-2, tji-service-3', max_length=100),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, help_text='Qeyd: şəklin ölçüsü 870 x 450 px olmalıdır', upload_to='service_images/'),
        ),
        migrations.AlterField(
            model_name='service',
            name='short_description',
            field=models.CharField(help_text='Qeyd: maximum 200 simvol', max_length=255),
        ),
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.CharField(help_text='Qeyd: maximum 200 simvol', max_length=200),
        ),
    ]
